<a href="https://colab.research.google.com/github/Singara-Harendra/PyTorch/blob/main/Pytorch_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
print(torch.__version__)

2.6.0+cu124


In [ ]:
if torch.cuda.is_available():
  print("CUDA is avvailable")
  print(f"Using Gpu:{torch.cuda.get_device_name(0)}")
else:
  print("GPU is not available")

GPU is not available


we can change to GPU using runtime->cahnge runtime type->GPP->save

#Creating Tensors

In [ ]:
#empty,dont initialise values and previous stored values at that location and the dimesions should be given as paras
a=torch.empty(2,3)

In [ ]:
type(a)

torch.Tensor

In [ ]:
#zeros,intialise all elements to zeroes

torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [ ]:
#ones

torch.ones(3,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
#rand,to initialise random numbers between 0 and 1

torch.rand(3,2)

tensor([[0.3401, 0.9559],
        [0.1844, 0.0394],
        [0.3514, 0.2499]])

In [ ]:
torch.rand(3,2)

tensor([[0.9593, 0.3904],
        [0.6009, 0.2566],
        [0.7936, 0.9408]])

In [ ]:
#when we use rand multiple times,diff numbers will be initialised and it will be a problem
#so, we got "manual_seed(value)"
#when we use manual_seed(value) with the same value then same rand numbers will be initialised everytime
# same seed will give you same random numbers

torch.manual_seed(42)
torch.rand(3,2)

tensor([[0.8823, 0.9150],
        [0.3829, 0.9593],
        [0.3904, 0.6009]])

In [ ]:
torch.manual_seed(42)
torch.rand(3,1)

tensor([[0.8823],
        [0.9150],
        [0.3829]])

In [ ]:
#using tensor
#we can use list,tuple etc

torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
#another ways
print("using arange->",torch.arange(0,10,2)) #(min,max,step)

print("using linspace->",torch.linspace(0,10,10)) #linspace=linearly spaced (min,max,count)

print("using eye->",torch.eye(5))  #eye=identity matrix(dimension)

print("using full->",torch.full((3,3),5))  #(m,n) and every ele=5


using arange-> tensor([0, 2, 4, 6, 8])
using linspace-> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye-> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full-> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


**Tensor Shape**

In [ ]:
a=torch.tensor([[12,2],[-10,9]])
a.shape

torch.Size([2, 2])

In [ ]:
torch.empty_like(a) #creates tensor shape like a and datatype too

tensor([[138277819264368,       239239408],
        [           1877,     68719477842]])

In [ ]:
print(torch.zeros_like(a))
print(torch.ones_like(a))


tensor([[0, 0],
        [0, 0]])
tensor([[1, 1],
        [1, 1]])


In [ ]:
torch.rand_like(a, dtype=torch.float32)

tensor([[0.1332, 0.9346],
        [0.5936, 0.8694]])

Error because rand will generate floats between 0 and 1,but a is of int datatype and explicitly mentioning dtype will solve erroe and takes only its shape not its dtype

**Tensor Data Types**

In [ ]:
#find datatype

a.dtype

torch.int64

In [ ]:
#assign datatype

torch.tensor([1.3,4.0,4.6,3] , dtype=torch.int32)  #it will take floor

tensor([1, 4, 4, 3], dtype=torch.int32)

In [ ]:
#using to()

a.to(torch.float32) #a is int and changeed to float

tensor([[ 12.,   2.],
        [-10.,   9.]])

**Operations on Tensors**

**1.Scalar Operations**

In [ ]:
a=torch.tensor([1,2,3,5,0])
#addition

print(a+3)

#substraction

print(a-2)

#multiplication

print(a*2)

#division

print(a/2)

#integer division

print(a//2)

#mod

print(a%2)

#power

print(a**2)



tensor([4, 5, 6, 8, 3])
tensor([-1,  0,  1,  3, -2])
tensor([ 2,  4,  6, 10,  0])
tensor([0.5000, 1.0000, 1.5000, 2.5000, 0.0000])
tensor([0, 1, 1, 2, 0])
tensor([1, 0, 1, 1, 0])
tensor([ 1,  4,  9, 25,  0])


**2.Element wise operations**
 (Shape should be exactly same)

In [ ]:
a=torch.rand(2,3)
b=torch.rand(2,3)
print(a)
b

tensor([[0.9207, 0.5442, 0.7458],
        [0.4173, 0.2053, 0.0348]])


tensor([[0.3250, 0.4861, 0.1387],
        [0.0919, 0.0779, 0.2415]])

In [ ]:
#add

a+b

#substraction

a-b
#multiplication
a*b
#division
a/b
#integer division
a//b
#power
a**b
#mod
a%b

tensor([[0.2708, 0.0581, 0.0525],
        [0.0499, 0.0494, 0.0348]])

In [ ]:
c=torch.tensor((1,-2,3,44))
id(c)

135184689093648

In [ ]:
#abs
torch.abs(c)

#neg
torch.neg(c)

tensor([ -1,   2,  -3, -44])

In [ ]:
d=torch.tensor([1.2,3.4,44,56,64.32,6.9])
#round
torch.round(d)

#ceil
torch.ceil(d)

#floor
torch.floor(d)

#clamp
torch.clamp(d,min=0,max=40)  #makes sure that every element lie in range or clampimg



tensor([ 1.2000,  3.4000, 40.0000, 40.0000, 40.0000,  6.9000])

**3.Reduction Operation**

In [ ]:
e=torch.tensor([[12,2,3,4],[2,3,5,6]],dtype=torch.float32)
e

tensor([[12.,  2.,  3.,  4.],
        [ 2.,  3.,  5.,  6.]])

In [ ]:
#sum
torch.sum(e)

tensor(26)

In [ ]:
#sum along column elements
torch.sum(e,dim=0)

tensor([ 3,  5,  8, 10])

In [ ]:
#sum along row elements
torch.sum(e,dim=1)

tensor([10, 16])

In [ ]:
#mean
torch.mean(e)   #dtype should be float

#mean along columns                                   ##DIM=0 for col and DIM=1 for rows
torch.mean(e,dim=0)

#mean along rows
torch.mean(e,dim=1)

tensor([2.5000, 4.0000])

In [ ]:
#median
torch.median(e)

##median canot be done on col or row wise

torch.return_types.median(
values=tensor([1., 2., 3., 4.]),
indices=tensor([0, 0, 0, 0]))

In [ ]:
#max,min
print(e)
torch.max(e)
torch.min(e)

tensor([[1., 2., 3., 4.],
        [2., 3., 5., 6.]])


tensor(1.)

In [ ]:
#prod
torch.prod(e)

tensor(4320.)

In [ ]:
e=torch.tensor([[12,33,4],[12,222,3]],dtype=torch.float32)

#std
torch.std(e)

#var
torch.var(e)

#argmax
torch.argmax(e)

#argmin
torch.argmin(e)  #it treats elements as 0,1,2,3... instead of [i][j]

tensor(5)

**4.Matrix Operations**

In [ ]:
f=torch.randint(size=(2,3),low=0,high=10)
g=torch.randint(size=(3,2),low=0,high=10)
print(f)
g

tensor([[0, 7, 9],
        [5, 6, 8]])


tensor([[2, 2],
        [7, 8],
        [4, 0]])

In [ ]:
#matmul
torch.matmul(f,g)

tensor([[85, 56],
        [84, 58]])

In [ ]:
#dot product
vector1=torch.tensor([1,2,3])      # everything is a function in keras,if two things needed means give two parameters like that
vector2=torch.tensor([3,4,5])
torch.dot(vector1,vector2)

tensor(26)

In [ ]:
#transpose
torch.transpose(f,0,1)

tensor([[0, 5],
        [7, 6],
        [9, 8]])

In [ ]:
h=torch.randint(size=(3,3),low=1,high=20,dtype=torch.float32)
h

tensor([[19., 11.,  7.],
        [ 8., 18., 16.],
        [19., 15., 11.]])

In [ ]:
#det
torch.det(h)

tensor(24.0001)

In [ ]:
#inverse
torch.inverse(h)

tensor([[ -1.7500,  -0.6667,   2.0833],
        [  9.0000,   3.1667, -10.3333],
        [ -9.2500,  -3.1667,  10.5833]])

**5.Comparision Operators**

In [ ]:
i=torch.randint(size=(2,3),low=0,high=10)
j=torch.randint(size=(2,3),low=0,high=10)
print(i)
j

tensor([[3, 9, 0],
        [6, 4, 8]])


tensor([[8, 8, 2],
        [5, 4, 7]])

In [ ]:
print(i>j)

tensor([[False,  True, False],
        [ True, False,  True]])


In [ ]:
print(i<=j)

tensor([[ True, False,  True],
        [False,  True, False]])


In [ ]:
print(i==j)

tensor([[False, False, False],
        [False,  True, False]])


In [ ]:
print(i!=j)

tensor([[ True,  True,  True],
        [ True, False,  True]])


**6.Special Functions**

In [ ]:
k=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
k

tensor([[2., 9., 7.],
        [6., 2., 2.]])

In [ ]:
#log
torch.log(k)

tensor([[1.7918,   -inf, 1.0986],
        [0.6931, 2.0794, 0.6931]])

In [ ]:
#exp
torch.exp(k)

tensor([[4.0343e+02, 1.0000e+00, 2.0086e+01],
        [7.3891e+00, 2.9810e+03, 7.3891e+00]])

In [ ]:
#sqrt
torch.sqrt(k)

tensor([[2.4495, 0.0000, 1.7321],
        [1.4142, 2.8284, 1.4142]])

In [ ]:
#sigmoid
torch.sigmoid(k)

tensor([[0.9975, 0.5000, 0.9526],
        [0.8808, 0.9997, 0.8808]])

In [ ]:
#sigmoid
torch.softmax(k,dim=0)

tensor([[1.7986e-02, 9.9909e-01, 9.9331e-01],
        [9.8201e-01, 9.1105e-04, 6.6929e-03]])

In [ ]:
#sigmoid
torch.softmax(k,dim=1)

tensor([[8.0254e-04, 8.8009e-01, 1.1911e-01],
        [9.6466e-01, 1.7668e-02, 1.7668e-02]])

In [ ]:
#relu
torch.relu(k)

tensor([[2., 9., 7.],
        [6., 2., 2.]])

**Inplace Operations**

In [ ]:
m=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
n=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
print(m)
n

tensor([[0., 6., 1.],
        [3., 7., 4.]])


tensor([[3., 9., 1.],
        [2., 4., 8.]])

In [ ]:
#m+n will create an another tensor
## but m.add_(n) will be inplace,means it will modify m tensor
m.add_(n)

tensor([[ 3., 15.,  2.],
        [ 5., 11., 12.]])

In [ ]:
m

tensor([[ 3., 15.,  2.],
        [ 5., 11., 12.]])

In [ ]:
#torch.relu(m) #will create another tensor but we can make it inplace
m.exp_()

tensor([[2.0086e+01, 3.2690e+06, 7.3891e+00],
        [1.4841e+02, 5.9874e+04, 1.6275e+05]])

In [ ]:
m      #m itself updated

tensor([[2.0086e+01, 3.2690e+06, 7.3891e+00],
        [1.4841e+02, 5.9874e+04, 1.6275e+05]])

**Copying a tensor**

In [ ]:
# same as of python list if a=b the a and b will points to same address

a=torch.rand(2,3,dtype=torch.float32)
b=a
a

tensor([[0.7453, 0.1651, 0.5386],
        [0.2702, 0.8798, 0.6988]])

In [ ]:
b

tensor([[0.7453, 0.1651, 0.5386],
        [0.2702, 0.8798, 0.6988]])

In [ ]:
a[0][0]=1
a

tensor([[1.0000, 0.1651, 0.5386],
        [0.2702, 0.8798, 0.6988]])

In [ ]:
b   #here b is also pointing to the same address as of a so modifying a will change b also

tensor([[1.0000, 0.1651, 0.5386],
        [0.2702, 0.8798, 0.6988]])

In [ ]:
id(a)

135184634011120

In [ ]:
id(b)

135184634011120

In [ ]:
#to stop this we use

#clone()
b=a.clone()

In [ ]:
b

tensor([[1.0000, 0.1651, 0.5386],
        [0.2702, 0.8798, 0.6988]])

In [ ]:
print(id(a))
print(id(b))   #both are at different places

135184634011120
135184357733584


In [ ]:
torch.cuda.is_available()

True

In [ ]:
device=torch.device('cuda')

In [ ]:
#creating a new tensor in GPU
torch.rand(2,3,device=device,dtype=torch.float32)

tensor([[0.9490, 0.8399, 0.9268],
        [0.4626, 0.3878, 0.0644]], device='cuda:0')

In [ ]:
#moving an existing tensor to gpu

a=torch.rand(2,3,dtype=torch.float32)
b=a.to(device)
print(a)
b

tensor([[0.7763, 0.8977, 0.6936],
        [0.6232, 0.1170, 0.2224]])


tensor([[0.7763, 0.8977, 0.6936],
        [0.6232, 0.1170, 0.2224]], device='cuda:0')

In [ ]:
b+5

tensor([[5.7763, 5.8977, 5.6936],
        [5.6232, 5.1170, 5.2224]], device='cuda:0')

**Checking time difference between cpu and gpu**

In [ ]:
import time

#creating two matrices in cpu
cpu_matrix_1=torch.randint(size=(1000,1000),low=0,high=1000,dtype=torch.float32)
cpu_matrix_2=torch.randint(size=(1000,1000),low=0,high=1000,dtype=torch.float32)
start_time=time.time()
cpu_res=torch.matmul(cpu_matrix_1,cpu_matrix_2)
end_time=time.time()
print(f"Time taken by cpu:{end_time-start_time}")

#creating tensors using gpu
gpu_matrix_1=cpu_matrix_1.to('cuda')
gpu_matrix_2=cpu_matrix_2.to('cuda')
gpu_start_time=time.time()
gpu_res=torch.matmul(gpu_matrix_1,gpu_matrix_2)
gpu_end_time=time.time()
print(f"Time taken by gpu:{gpu_end_time-gpu_start_time}")

print(f"Time difference of gpu_time/cpu_time : {((end_time-start_time)/(gpu_end_time-gpu_start_time))}")

Time taken by cpu:0.03828310966491699
Time taken by gpu:0.00027370452880859375
Time difference of gpu_time/cpu_time : 139.87020905923345


**Reshaping Tensors**

In [ ]:
a=torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
#reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [ ]:
#flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
torch.flatten(a)

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
#permute
b=torch.randint(size=(2,3,4),low=0,high=10)
b

tensor([[[9, 0, 0, 7],
         [7, 2, 5, 6],
         [3, 6, 9, 9]],

        [[3, 2, 8, 4],
         [7, 7, 5, 8],
         [2, 1, 8, 9]]])

In [ ]:
b.permute(1,2,0).shape  ##le,breadth and height is changed

torch.Size([3, 4, 2])

In [ ]:
#unsqueeze,means i am including a layer like that
b.unsqueeze(0).shape  #a layer is inserted at 0 place

torch.Size([1, 2, 3, 4])

In [ ]:
#squeeze,means reducing its shape

b=torch.rand(1,20)
b.shape

torch.Size([1, 20])

In [ ]:
b.squeeze(0).shape

torch.Size([20])

**NumPy and PyTorch**

In [ ]:
import numpy as np


In [ ]:
#tensor to array

a=torch.tensor([1,2,3,4,5])
print(type(a))
b=a.numpy()
print(type(b))

<class 'torch.Tensor'>
<class 'numpy.ndarray'>


In [ ]:
#numpy array to tensor

a=np.array([1,23,4,5])
b=torch.from_numpy(a)
b

tensor([ 1, 23,  4,  5])